### ISSUE TITLE
How to get refs after added?

### ISSUE THREAD

**Issue by chrisdel101** [Macil/react-multi-ref#2]
Hi,
I've setup your example as I need to add refs to a huge number of dynamically created components. I look at the `items` array from the example and the refs are null in each obj. If I have many items, and I need to target say ref#1037, how would I do that? 

How do I access the refs after attached? `i.e const node = this.myRef.current;`

**Comment by Macil** [comment]
Assuming `this.myRef` is a MultiRef object, you can do `const node = this.myRef.map.get(1037);`. Let me know if that helps you. I think I should update the example to make it more clear.

**Comment by chrisdel101** [comment]
I get back an array of 5 objs but I don't think they are the right objs. So..this is a timing issue on my end. I get this if I log too soon.

    `{ 
    $$typeof: Symbol(react.element)
    key: "0"
    props: {children: {…}}
    ref: null
    type: "div"
    _owner: FiberNode {tag: 1, key: null, elementType: ƒ, type: ƒ, stateNode: Box, …}
    _store: {validated: false}
    _self: null
    _source: {fileName: 
    "/Box.js", lineNumber: 11}
    __proto__: Object
    }`

I see how it works when I do it properly. This would have been more obvious had I done it right. Thanks for clarifying!!

PS - a line such as U posted for me would be helpful in the docs!
