### ISSUE TITLE
Usage with Flow

### ISSUE THREAD

**Issue by sandgraham** [Macil/react-multi-ref#7]
Hi there, I was trying to use this in a project that has Flow types but am having some trouble. The actual functionality works- I am able to access multiple dynamically created refs, but the types in my component are not right and I'm not sure how to fix them.

Here is an example of the sort of component I am trying to create. I've simplified it just to showcase how I am using the refs:
```js
// @flow

import React from "react";
import MultiRef from "react-multi-ref";

class Foo extends React.Component {
  constructor(props) {
    super(props);
    this._inputRefs = new MultiRef(); // Flow issues start here
  }

  render() {
    return (
      <React.Fragment>
        <input
          ref={this._inputRefs.ref(1)}
          onFocus={() => this._inputRefs.map.get(1).current.select()}
        />
        <input
          ref={this._inputRefs.ref(2)}
          onFocus={() => this._inputRefs.map.get(2).current.select()}
        />
      </React.Fragment>
    );
  }
}
```

Flow complains about `this._inputRefs` not being typed. But once I started trying to type that manually, Flow complains about mismatches with `MultiRef`. 

Perhaps my question then is what generic types should I provide to the `MultiRef<K, V>` and how should I type `this._inputRefs`? The examples in the README don't seem to explicitly type anything so I wasn't sure if there was a simple way do this.

Would appreciate help- Thanks!

**Comment by Macil** [comment]
This should work:

```js
// @flow

import React from "react";
import MultiRef from "react-multi-ref";

class Foo extends React.Component {
  _inputRefs = new MultiRef<number, HTMLInputElement>();

  render() {
    return (
      <React.Fragment>
        <input
          ref={this._inputRefs.ref(1)}
          onFocus={() => this._inputRefs.map.get(1).select()}
        />
        <input
          ref={this._inputRefs.ref(2)}
          onFocus={() => this._inputRefs.map.get(2).select()}
        />
      </React.Fragment>
    );
  }
}
```

You need to declare the property, and supply type parameters to MultiRef's constructor.

(Also, the return value of `this._inputRefs.map.get(1)` is the element itself, not a ref object with a current property.)

**Comment by sandgraham** [comment]
Declaring `_inputRefs = new MultiRef<number, HTMLInputElement>();` outside of the constructor made everything click into place.

I thought the class property syntax was just syntactic sugar for assigning things in the constructor (`this.foo = "blah"`) but I guess there is a difference for Flow.

Thanks for your help and work on this tool!

**Comment by Macil** [comment]
Technically I did an extra change in my code. It wasn't necessary for me to move the initialization outside of the constructor. The important thing is that the property is declared. It doesn't matter where it gets initialized. This should work too:

```js
class Foo extends React.Component {
  _inputRefs: MultiRef<number, HTMLInputElement>;
  constructor(props) {
    super(props);
    this._inputRefs = new MultiRef();
  }
```
